function x0Sym = x0Zenteno(in1)
%x0Zenteno
%    x0Sym = x0Zenteno(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    27-May-2022 17:00:21

x0Sym = [1.0./5.0;1.737e-1;1.1555e+2;1.0094e+2;0.0];
