function x0Sym = x0Samada(in1)
%x0Samada
%    x0Sym = x0Samada(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    11-Jun-2022 18:33:15

x0Sym = [1.0./5.0e+1;8.53e+2./1.0e+3;8.1e+1./1.0e+1;1.2e+1./2.5e+1;0.0;4.13e+2./5.0e+1;3.0./4.0e+1];
