function dx0dthSym = dICdthSamada(in1,in2)
%dICdthSamada
%    dx0dthSym = dICdthSamada(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    03-Jul-2022 23:17:30

dx0dthSym = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[7,7]);
