function dx0dthSym = dICdthZenteno(in1,in2)
%dICdthZenteno
%    dx0dthSym = dICdthZenteno(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    27-May-2022 17:00:21

dx0dthSym = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,11]);
