function x0Sym = x0Samada(in1)
%x0Samada
%    x0Sym = x0Samada(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    03-Jul-2022 14:48:45

x0Sym = [1.0095e+2;7.0./5.0;9.9e+1./1.25e+2;4.7e+1./1.0e+3;1.0e-9;3.03e+2./1.0e+2;3.0./4.0e+1];
